// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    GameArea: typeof import('./src/components/GameArea.vue')['default']
    Idiom: typeof import('./src/components/Idiom.vue')['default']
    Word: typeof import('./src/components/Word.vue')['default']
  }
}

export { }
